[package]
publish = false
name = "interface"
version = "0.0.1"
edition = "2021"

[dependencies]
domain = { workspace = true, features = ["dto"] }
interface-traits = { path = "../interface-traits" }

candid.workspace = true
derive_more = "2.0"
serde.workspace = true
